version: '3.8'

services:
  streamsets-mcp:
    build: .
    container_name: streamsets-mcp-server
    environment:
      # StreamSets Configuration (required)
      - STREAMSETS_HOST_PREFIX=${STREAMSETS_HOST_PREFIX}
      - STREAMSETS_CRED_ID=${STREAMSETS_CRED_ID}
      - STREAMSETS_CRED_TOKEN=${STREAMSETS_CRED_TOKEN}
      # Pipeline builder persistence configuration
      - PIPELINE_STORAGE_PATH=/data/pipeline_builders
    volumes:
      # Pipeline builder persistence volume
      - pipeline_data:/data
      # Alternative: bind mount to host directory
      # - ./data:/data
    stdin_open: true
    tty: true
    # Networking for MCP communication
    network_mode: host
    restart: unless-stopped

    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import streamsets_server; print('OK')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  # Named volume for pipeline builder persistence
  pipeline_data:
    driver: local